title: borjan geshkovski
author: Borjan Geshkovski
# subtitle: 

url: "https://borjanG.github.io"
baseurl: 

footer_only_homepage: true
footer_url: ""
footer_text: ""

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Vita"
   link: "about"
 - name: "Publications"
   absolute-link: "https://scholar.google.com/citations?user=XxCmLvoAAAAJ&hl=en"
 - name: "Code"
   absolute-link: "https://github.com/borjanG"
 - name: "Contact"
   link: "contact"

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true