title: borjan geshkovski
author: Borjan Geshkovski
# subtitle: 

url: "https://borjanG.github.io"
baseurl: 

footer_only_homepage: true
footer_url: ""
footer_text: ""

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico
hover-picture: assets/hover.jpg
cv: assets/CV-Geshkovski.pdf
rapport_inria: assets/rapport_inria.pdf
rapport_harmonique: assets/rapport_harmonique.pdf

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Vita"
   link: "about"
 - name: "Publications"
   absolute-link: "https://scholar.google.com/citations?user=XxCmLvoAAAAJ&hl=en"
 - name: "Talks"
   link: "talks"
 - name: "Code"
   absolute-link: "https://github.com/borjanG"
 - name: "Things"
   link: "things"

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true