title: bLog(Likelihood)
author: Xinkai Zhou
# subtitle: 

url: "https://xinkai-zhou.github.io"
baseurl: 

footer_only_homepage: true
footer_url: ""
footer_text: ""

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Publications"
   absolute-link: "https://scholar.google.be/citations?user=UXNdqWgAAAAJ&hl=en&oi=ao"
 - name: "CV"
   absolute-link: "CV.pdf"

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true